# Generated by Django 4.0.6 on 2024-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('day_start', models.IntegerField(default=1)),
                ('month_start', models.IntegerField(default=1)),
                ('day_end', models.IntegerField(default=31)),
                ('month_end', models.IntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leave Contract',
                'verbose_name_plural': 'Leave Contract',
                'db_table': 'ftb_eleave_leave_contract',
                'managed': True,
            },
        ),
    ]
