# Generated by Django 4.0.6 on 2024-04-19 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_contract', '0001_initial'),
        ('leave_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavecontractmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leavecontractmodel',
            name='default_leave_type',
            field=models.ForeignKey(blank=True, db_column='default_leave_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='leave_type.leavetypemodel'),
        ),
        migrations.AddField(
            model_name='leavecontractmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
