# Generated by Django 4.0.6 on 2024-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='<u>Leave type name for sick leave, you must input this name for sick leave:</u> Sick Leave', max_length=255, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=255, null=True)),
                ('deduct_days_off', models.BooleanField(default=True)),
                ('entitle_balance', models.FloatField(default=0, max_length=255)),
                ('additional_balance', models.FloatField(default=0, max_length=255)),
                ('HOOK_KEY', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Leave Type',
                'verbose_name_plural': 'Leave Types',
                'db_table': 'ftb_eleave_leave_type',
                'managed': True,
            },
        ),
    ]
