version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3030:3000" # Access Grafana by navigating to http://<host-ip>:3030.
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage: {}

# How to run:
# cd project dir
# docker-compose -f monitoring/grafana.compose.yml up -d
# docker-compose -f grafana.compose.yml up -d