version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090 # Access Prometheus's web interface via http://<host-ip>:9090.
    restart: unless-stopped
    volumes:
      - volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  prom_data:
  grafana-storage: {}


# docker-compose -f monitoring/monitoring.compose.yml up -d
# Access Grafana by navigating to http://localhost:3000
# Access Prometheus by navigating to http://localhost:9090