version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090 # Access Grafana by navigating to http://<host-ip>:9090.
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prom_data:/prometheus
volumes:
  prom_data:


# docker-compose -f monitoring/prometheus.compose.yml up --build -d
# docker-compose -f prometheus.compose.yml up --build -d