# Generated by Django 4.0.6 on 2024-04-19 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_request', '0001_initial'),
        ('leave_type', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequeststatus',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequeststatus',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='authorizer',
            field=models.ForeignKey(blank=True, db_column='authorizer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_authorizer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='authorizer_by',
            field=models.ForeignKey(blank=True, db_column='authorizer_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_authorizer_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='canceled_by',
            field=models.ForeignKey(blank=True, db_column='canceled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_canceled_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='certifier',
            field=models.ForeignKey(blank=True, db_column='certifier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_certifier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='certifier_by',
            field=models.ForeignKey(blank=True, db_column='certifier_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_certifier_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_status', to='leave_request.leaverequeststatus'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_type', to='leave_type.leavetypemodel'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, db_column='rejected_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_rejected_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_column='requested_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_requested_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
