# Generated by Django 4.0.6 on 2024-04-19 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('entitle_balance', models.FloatField(blank=True, default=0, null=True)),
                ('additional_balance', models.FloatField(blank=True, default=0, null=True)),
                ('forward_balance', models.FloatField(blank=True, default=0, null=True)),
                ('begin_annual_leave', models.FloatField(blank=True, default=0, null=True)),
                ('taken_annual_leave', models.FloatField(blank=True, default=0, null=True)),
                ('current_annual_leave', models.FloatField(blank=True, default=0, null=True)),
                ('begin_sick_leave', models.FloatField(blank=True, default=0, null=True)),
                ('taken_sick_leave', models.FloatField(blank=True, default=0, null=True)),
                ('current_sick_leave', models.FloatField(blank=True, default=0, null=True)),
                ('begin_special_leave', models.FloatField(blank=True, default=0, null=True)),
                ('taken_special_leave', models.FloatField(blank=True, default=0, null=True)),
                ('current_special_leave', models.FloatField(blank=True, default=0, null=True)),
                ('begin_maternity_leave', models.FloatField(blank=True, default=0, null=True)),
                ('taken_maternity_leave', models.FloatField(blank=True, default=0, null=True)),
                ('current_maternity_leave', models.FloatField(blank=True, default=0, null=True)),
                ('begin_unpaid_Leave', models.FloatField(blank=True, default=0, null=True)),
                ('taken_unpaid_leave', models.FloatField(blank=True, default=0, null=True)),
                ('current_unpaid_leave', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Leave balance',
                'verbose_name_plural': 'Leave balance',
                'db_table': 'ftb_eleave_leave_balance',
                'managed': True,
            },
        ),
    ]
