# Generated by Django 4.0.6 on 2024-04-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name_en', models.CharField(default=None, max_length=255, unique=True)),
                ('menu_name_kh', models.CharField(default=None, max_length=255, unique=True)),
                ('menu_icon', models.CharField(default=None, max_length=100)),
                ('module_url', models.CharField(db_column='module_url', default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Item',
                'db_table': 'ftb_menu_item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MenuOrderable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderable', models.TextField(blank=True, default='[]', null=True)),
            ],
            options={
                'verbose_name': 'Menu Orderable',
                'verbose_name_plural': 'Menu Orderable',
                'db_table': 'ftb_menu_orderable',
                'managed': True,
            },
        ),
    ]
