# Generated by Django 4.0.6 on 2024-04-19 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisee',
            field=models.OneToOneField(db_column='appraisee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraiser',
            field=models.OneToOneField(db_column='appraiser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraiser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='template',
            field=models.ForeignKey(db_column='template', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.template'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='updated_by',
            field=models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appraisal_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
